### ISSUE TITLE
Package Managers

### ISSUE THREAD

**Issue by erwstout** [Heydon/forceFeed#1]
Thoughts on adding bower and npm as package manager options?

**Comment by Heydon** [comment]
@buschschwick Yes, I've been thinking about this. Thoughts on the structure of the npm package? It's just a DOM manip script, so I'm unsure how it fits in with Node. If you could suggest a folder structure, great!

**Comment by danreeves** [comment]
You can do something like:

``` js
if (typeof define === 'function' && define['amd']) {
    define(function() { return forceFeed; });
} else if (typeof module !== 'undefined' && module['exports']) {
    module['exports'] = forceFeed;
} else if (typeof window !== 'undefined') {
    window['forceFeed'] = forceFeed;
}
```

in place of `window.forceFeed = forceFeed` at the bottom of the IIFE. Then you just need a `package.json` and `bower.json` pointing at the file.

**Comment by aderaaij** [comment]
I don't think it needs much of a structure, does it? Just the flat files, like this: https://github.com/dinbror/blazy

**Comment by erwstout** [comment]
I agree with @aderaaij - personally I would just include the path to the `.js` file when I compile with Gulp.

The package would be a plus so that it could be included as a dev dependency for the project.

**Comment by Heydon** [comment]
Thanks to @Munter!
