### ISSUE TITLE
More possibilities

### ISSUE THREAD

**Issue by SimonWpt** [Heydon/forceFeed#3]
Why not add more infos, i.e.:
- sentence
- word
- paragraph
- date
- name
- first_name
- last_name
- initials
- email
- domain
- street
- city
- zipcode
- country
- image

**Comment by Heydon** [comment]
Interesting thought. The script is really just designed to test varying _quantities_ of content, though. Since dates and zipcodes would be a set length, is there need for that? I wonder if another script is available somewhere that covers all this?

**Comment by SimonWpt** [comment]
Something like this:
https://github.com/blahed/frank#placeholder-text

**Comment by Heydon** [comment]
@SimonWpt Yeah, that looks good for your purposes?

**Comment by WickyNilliams** [comment]
I've used http://chancejs.com/ for this kind of thing in the past

**Comment by Heydon** [comment]
The way forceFeed is designed, _you_ get to define arrays (libraries) of content, so you can set up a random date array or even generate them. It's just a little API with some easy randomness built in. What you "feed" it could be anything.
